settings:
  fire_spread_chance: 0.02  # Chance of fire spreading (deafault: 0.02)
  fire_spread_interval: 5 # Seconds between fire spread attempts (default: 5)
  lava_spreads_fire: true # Lava spreads fire to the set custom blocks (default: true)
  debug_mode: false
  
custom_blocks:
  mode: "whitelist"  # Whitelist or blacklist blocks from being flammable. Blacklist mode sets all blocks except blacklisted ones to be flammable
  
  # Use Spigot API block names
  whitelist_blocks: [CHEST, CRAFTING_TABLE] 
  blacklist_blocks: [BARRIER, BEDROCK, STONE, GRASS_BLOCK, DIRT, TNT, WATER, COMMAND_BLOCK, CHAIN_COMMAND_BLOCK, REPEATING_COMMAND_BLOCK, STRUCTURE_BLOCK,
  ACACIA_LEAVES, BIRCH_LEAVES, DARK_OAK_LEAVES, JUNGLE_LEAVES, OAK_LEAVES, SPRUCE_LEAVES,
  ACACIA_LOG, BIRCH_LOG, DARK_OAK_LOG, JUNGLE_LOG, OAK_LOG, SPRUCE_LOG,
  ACACIA_PLANKS, BIRCH_PLANKS, DARK_OAK_PLANKS, JUNGLE_PLANKS, OAK_PLANKS, SPRUCE_PLANKS,
  ACACIA_WOOD, BIRCH_WOOD, DARK_OAK_WOOD, JUNGLE_WOOD, OAK_WOOD, SPRUCE_WOOD,
  STRIPPED_ACACIA_LOG, STRIPPED_BIRCH_LOG, STRIPPED_DARK_OAK_LOG, STRIPPED_JUNGLE_LOG, STRIPPED_OAK_LOG, STRIPPED_SPRUCE_LOG,
  STRIPPED_ACACIA_WOOD, STRIPPED_BIRCH_WOOD, STRIPPED_DARK_OAK_WOOD, STRIPPED_JUNGLE_WOOD, STRIPPED_OAK_WOOD, STRIPPED_SPRUCE_WOOD,
  ACACIA_SLAB, BIRCH_SLAB, DARK_OAK_SLAB, JUNGLE_SLAB, OAK_SLAB, SPRUCE_SLAB,
  ACACIA_STAIRS, BIRCH_STAIRS, DARK_OAK_STAIRS, JUNGLE_STAIRS, OAK_STAIRS, SPRUCE_STAIRS,
  ACACIA_FENCE, BIRCH_FENCE, DARK_OAK_FENCE, JUNGLE_FENCE, OAK_FENCE, SPRUCE_FENCE,
  ACACIA_FENCE_GATE, BIRCH_FENCE_GATE, DARK_OAK_FENCE_GATE, JUNGLE_FENCE_GATE, OAK_FENCE_GATE, SPRUCE_FENCE_GATE,
  ACACIA_DOOR, BIRCH_DOOR, DARK_OAK_DOOR, JUNGLE_DOOR, OAK_DOOR, SPRUCE_DOOR,
  ACACIA_TRAPDOOR, BIRCH_TRAPDOOR, DARK_OAK_TRAPDOOR, JUNGLE_TRAPDOOR, OAK_TRAPDOOR, SPRUCE_TRAPDOOR,
  ACACIA_BUTTON, BIRCH_BUTTON, DARK_OAK_BUTTON, JUNGLE_BUTTON, OAK_BUTTON, SPRUCE_BUTTON,
  ACACIA_PRESSURE_PLATE, BIRCH_PRESSURE_PLATE, DARK_OAK_PRESSURE_PLATE, JUNGLE_PRESSURE_PLATE, OAK_PRESSURE_PLATE, SPRUCE_PRESSURE_PLATE,
  ACACIA_SIGN, BIRCH_SIGN, DARK_OAK_SIGN, JUNGLE_SIGN, OAK_SIGN, SPRUCE_SIGN,
  WOOL, WHITE_WOOL, ORANGE_WOOL, MAGENTA_WOOL, LIGHT_BLUE_WOOL, YELLOW_WOOL, LIME_WOOL, PINK_WOOL, GRAY_WOOL,
  LIGHT_GRAY_WOOL, CYAN_WOOL, PURPLE_WOOL, BLUE_WOOL, BROWN_WOOL, GREEN_WOOL, RED_WOOL, BLACK_WOOL,
  BOOKSHELF, TALL_GRASS, DEAD_BUSH, VINE, LADDER, CARPET, LEGACY_WOOD, LEGACY_WOOD_DOUBLE_STEP, LEGACY_WOOD_STEP,
  LEGACY_WOODEN_DOOR, LEGACY_WOOD_STAIRS, LEGACY_WOOD_BUTTON, LEGACY_FENCE, LEGACY_FENCE_GATE,
  LEGACY_WOOD_PLATE, LEGACY_TRAP_DOOR, LEGACY_HUGE_MUSHROOM_1, LEGACY_HUGE_MUSHROOM_2, LEGACY_LEAVES_2,
  LEGACY_LOG_2, LEGACY_WOODEN_SLAB, LEGACY_BIRCH_WOOD_STAIRS, LEGACY_JUNGLE_WOOD_STAIRS, LEGACY_SPRUCE_WOOD_STAIRS,
  NOTE_BLOCK, TARGET, HAY_BLOCK, BAMBOO, NETHERRACK, SOUL_SAND, SOUL_SOIL, BASALT, POLISHED_BASALT, BLACKSTONE, POLISHED_BLACKSTONE, POLISHED_BLACKSTONE_BRICKS, CRIMSON_NYLIUM, WARPED_NYLIUM,
  CRIMSON_STEM, WARPED_STEM, STRIPPED_CRIMSON_STEM, STRIPPED_WARPED_STEM, CRIMSON_PLANKS, WARPED_PLANKS, CRIMSON_SLAB, WARPED_SLAB, CRIMSON_STAIRS, WARPED_STAIRS, CRIMSON_FENCE, WARPED_FENCE, LAVA]
  

